- params:
    git:
      repoName: frogbot-demo
      branches:
        - main
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: true
      projects:
        - installCommand: npm i
          workingDirs:
            - .