- params:
    git:
      repoName: frogbot-demo
      branches:
        - main
    scan:
      projects:
        - installCommand: npm i
          workingDirs:
            - .
    jfrogPlatform:
      watches:
        - frogbot-test-watch