
name: 'Frogbot Test'
on: [push]
jobs:
 jfrog-ci-integration:
   runs-on: ubuntu-latest
   env:
     JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'adopt'
     - name: Build
       run: |
         # config thing
         npm config fix
         # get version
         echo $(jf -v)
         # Configure the project
         jf npmc --server-id-resolve jfrog-instance --repo-resolve default-npm-remote --repo-deploy frogbot-demo-local
         # Build the project using JFrog CLI
         jf rt npmi
     - name: Failure check
       run: |
         echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
       if: failure()
     - name: Publish build
       run: |
         # Collect and store environment variables in the build-info
         jf rt bce
         # Collect and store VCS details in the build-info
         jf rt bag
         # Publish the build-info to Artifactory
         jf rt bp
         # Scan the published build-info with Xray
         # jf bs
       if: always()